language: go

go:
  - 1.5.1

services:
  - postgresql

addons:
  postgresql: "9.4"

sudo: false

script: "go test ./..."

before_install:
  - export PATH=$GOPATH/bin:$PATH
  - export DATABASE_URL=postgres://postgres@localhost:5432/mms_test?sslmode=disable
  - export PORT=3000
  - export ENV=test

before_script:
  - psql -c 'create database mms_test;' -U postgres
